export const posts =  [
  {
    id: 1,
    username: "Naing Linn Phyo",
    post: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    ago: "45m",
    isLike: true,
  },
  {
    id: 2,
    username: "Naing Linn Phyo",
    post: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    ago: "49m",
    isLike: false,
  },
  {
    id: 3,
    username: "David Jones",
    post: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    ago: "30m",
    isLike: true,
  },
  {
    id: 4,
    username: "Tom Barly",
    post: "I The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    ago: "20m",
    isLike: true,
  },
  {
    id: 5,
    username: "Tom Barly",
    post: "To using 'Content here, content here', making it look like readable English.",
    ago: "20m",
    isLike: true,
  },
  {
    id: 6,
    username: "Tom Barly",
    post: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    ago: "20m",
    isLike: false,
  },
  {
    id: 7,
    username: "Tom Barly",
    post: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    ago: "20m",
    isLike: true,
  },
  {
    id: 8,
    username: "Tom Barly",
    post: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    ago: "20m",
    isLike: false,
  },
  {
    id: 9,
    username: "Tom Barly",
    post: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    ago: "20m",
    isLike: false,
  },
  {
    id: 10,
    username: "Tom Barly",
    post: "Content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    ago: "20m",
    isLike: false,
  },
];
